# fly.toml app configuration file generated for papanmemorial on 2024-04-22T14:02:18+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'papanmemorial'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 4010
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
